### ISSUE TITLE
Some problems with train & eval

### ISSUE THREAD

**Issue by junhocho** [yikang-li/MSDN#1]
Thank you for your detailed project explanation.

With your provided data and code, I've been trying training and eval.

While training, your readme states:
` CUDA_VISIBLE_DEVICES=0 python train_rpn_region.py` 
You mean `train_rpn_region.py` as `train_rpn.py`?

Also, I can't find `faster_rcnn.roi_data_layer.roidb`

Furthermore, with evaluation code, 
`RPN_v3` module doesn't exist. Do you mean `from RPN_v3 import RPN` as  `from RPN import RPN`?

Also, eval still doesn't work with error, I still have following error:
```
➜  MSDN git:(master) ✗ bash eval.sh
Traceback (most recent call last):
  File "train_hdn.py", line 13, in <module>
    from faster_rcnn.MSDN import Hierarchical_Descriptive_Model
  File "/home/junho/MSDN/faster_rcnn/MSDN.py", line 45, in <module>
    class Hierarchical_Descriptive_Model(MSDN_base):
NameError: name 'MSDN_base' is not defined
```

`eval.sh` is your provided eval code
```
CUDA_VISIBLE_DEVICES=0 python train_hdn.py \   
	--resume_training --resume_model ./pretrained_models/HDN_1_iters_alt_normal_I_LSTM_with_bias_with_dropout_0_5_nembed_256_nhidden_512_with_region_regression_resume_SGD_best.h5 \   
	--dataset_option=normal  --MPS_iter=1 \   
	--caption_use_bias --caption_use_dropout \   
	--rnn_type LSTM_normal
```

I am referring faster-rcnn code (https://github.com/longcw/faster_rcnn_pytorch) but still need some help because your implementation is fork version of it.
Thank you very much for releasing the code.

**Comment by yikang-li** [comment]
Hi Junho, 

Thank you for your interest in our work. 

Sorry for troubling you due to my mistake. I have fixed the bug. Now it can run appropriately. 

If you have any further problems, please feel free to contact me. 

Best,
Yikang
