### ISSUE TITLE
Failed to use the caption function in faster_rcnn/MSDN.py

### ISSUE THREAD

**Issue by Sisi0518** [yikang-li/MSDN#10]
when I put an img_path in the caption function in faster_rcnn/MSDN.py, I got the error 
"File "/home/wangsijin/projects/new_MSDN/faster_rcnn/RPN.py", line 127, in forward
    im_data = Variable(im_data.cuda())
AttributeError: 'numpy.ndarray' object has no attribute 'cuda'"

 Then I translated the  ndarray to a tensor using "torch.from_numpy()" and got the error  
"RuntimeError: Given groups=1, weight[64, 3, 3, 3], so expected input[1, 600, 800, 3] to have 3 channels, but got 600 channels instead"

Then I used the ".transpose()" to transpose the 1*600*800*3 tensor to 1*3*600*800 tensor. And I got an error again
"File "/home/wangsijin/projects/new_MSDN/faster_rcnn/network.py", line 64, in np_to_variable
    v = Variable(torch.from_numpy(x).type(dtype))
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch"

I don't know how to solve it and  hope someone can help me. Thanks a lot.

**Comment by yikang-li** [comment]
Sorry, we didn't include the "dense caption" part in the released version.
