### ISSUE TITLE
About training set

### ISSUE THREAD

**Issue by wangxinyu0922** [yikang-li/MSDN#11]
Hi, thank you for your nice code.
In section 4.1 of the paper, you mention that the training set contains 70998 images, however the provided cleansed Visual Genome dataset contains 46164 images for training. What's the difference between the two dataset and do they provide similar result?
Thank you

**Comment by yikang-li** [comment]
We further cleansed some image instances with few objects/relationships. Evaluated with Recall, the released version is harder than the version used in the original paper. We continue using this dataset in our newly released project: https://github.com/yikang-li/FactorizableNet
