### ISSUE TITLE
GRU Unit

### ISSUE THREAD

**Issue by liren2515** [yikang-li/MSDN#12]
Hi, in your code, there is GRU unit. I know it's used to update the feature. But from your code, it seems not exactly like what you said in your paper	. To my understanding, there will be a FC layer on object_sub and another different FC layer on object_obj. But in your code, it seems you calculate the average of object_sub and object_obj, and then use one FC layer on that average and another FC on feature_obj. Did I understand something wrong?

```
GRU_input_feature_object = (object_sub + object_obj) / 2.
out_feature_object = feature_obj + self.GRU_object(GRU_input_feature_object, feature_obj)	
```

**Comment by yikang-li** [comment]
Yes, you are right. Sorry, I forgot why I do this. But this can be viewed as a weight-sharing for the expected FC layers. Theoretically, two FCs should be different. But I don't think this will significantly influence the final results. 

If possible, you are highly encouraged to modify the code by yourself and check the influence. Please let me know if you need any help. 

Also I recommend our latest project on scene graph generation: https://github.com/yikang-li/FactorizableNet
