### ISSUE TITLE
loss : nan problem

### ISSUE THREAD

**Issue by jungjun9150** [yikang-li/MSDN#17]
thank you for your nice code
I am studying your paper MSDN.
so i tried to implement your code.
I successfully implemented your code but,  I got this ploblem

Epoch: [0][1000/15000] [lr: 0.01] [Solver: SGD]
	Batch_Time:  0.322s	FRCNN Loss:  nan	RPN Loss:  0.9130
	[Loss]	obj_cls_loss: nan	obj_box_loss: nan 	pred_cls_loss: nan, 	caption_loss: 9.0235, 	region_box_loss: nan,  	region_objectness_loss: nan 
	[object]	tp: 0.00, 	tf: 0.00, 	fg/bg=(46/175)
	[predicate]	tp: 0.00, 	tf: 0.00, 	fg/bg=(99/412)
	[region]	tp: 0.00, 	tf: 0.00, 	fg/bg=(48/76)

Most loss is Nan ...
there is no warning in console.
if you know the reason why of this problem..give me some help. 

thank you!!

**Comment by TP0609** [comment]
> thank you for your nice code
> I am studying your paper MSDN.
> so i tried to implement your code.
> I successfully implemented your code but, I got this ploblem
> 
> Epoch: [0][1000/15000] [lr: 0.01] [Solver: SGD]
> Batch_Time: 0.322s FRCNN Loss: nan RPN Loss: 0.9130
> [Loss] obj_cls_loss: nan obj_box_loss: nan pred_cls_loss: nan, caption_loss: 9.0235, region_box_loss: nan, region_objectness_loss: nan
> [object] tp: 0.00, tf: 0.00, fg/bg=(46/175)
> [predicate] tp: 0.00, tf: 0.00, fg/bg=(99/412)
> [region] tp: 0.00, tf: 0.00, fg/bg=(48/76)
> 
> Most loss is Nan ...
> there is no warning in console.
> if you know the reason why of this problem..give me some help.
> 
> thank you!!

hello!  how do you inplemented the MSDN code? can you send you email to me? thank you !

**Comment by yikang-li** [comment]
Please check our latest project. Thanks. 
https://github.com/yikang-li/FactorizableNet
