### ISSUE TITLE
unable to Build the Cython modules for nms and the roi_pooling layer

### ISSUE THREAD

**Issue by faaizhashmi** [yikang-li/MSDN#18]
Hi!
I am studying your paper on MSDN and trying to run your model on my computer. When i try to execute cd MSDN-master/faster_rcnn **./make.sh** It gives the following error

![Screenshot from 2019-08-19 02-34-57](https://user-images.githubusercontent.com/30311213/63230714-fa484a00-c229-11e9-9c17-0bc85a1aac54.png)
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 52, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Compiling roi pooling kernels by nvcc...
./make.sh: line 10: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Please help if you know anything about the error i am getting

**Comment by CodHeK** [comment]
Use pytorch version 0.4.1

**Comment by TP0609** [comment]
> Use pytorch version 0.4.1

hello, Do you know the version of python and cuda  with MSDN? thank you !

**Comment by yikang-li** [comment]
> > Use pytorch version 0.4.1
> 
> hello, Do you know the version of python and cuda with MSDN? thank you !

python 2.7

**Comment by TP0609** [comment]
Hello !

　　 When I reproduce the MSDN code now, run: CUDA_VISIBLE_DEVICES = 0 python train_rpn.py

An error occurred:　
  [  3   6   4]
  [  3   6   4]
  [  5   6   4]]]
/home/tp/MSDN-master/faster_rcnn/RPN.py:140: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob = F.softmax(rpn_cls_score_reshape)
/home/tp/.local/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train_rpn.py", line 194, in <module>
    main()
  File "train_rpn.py", line 73, in main
    train(train_loader, net, optimizer, epoch)
  File "train_rpn.py", line 117, in train
    target_net(im_data, im_info.numpy(), gt_objects.numpy()[0], gt_regions.numpy()[0])
  File "/home/tp/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tp/MSDN-master/faster_rcnn/RPN.py", line 182, in forward
    self.build_loss(rpn_cls_score_reshape, rpn_bbox_pred, rpn_data)
  File "/home/tp/MSDN-master/faster_rcnn/RPN.py", line 239, in build_loss
    rpn_loss_box = F.smooth_l1_loss(rpn_bbox_pred, rpn_bbox_targets, size_average=False) /(fg_cnt + 1e-4)
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'






Traceback (most recent call last):
  File "/home/tp/MSDN-master/faster_rcnn/MSDN.py", line 19, in <module>
    from rpn_msr.proposal_layer import proposal_layer as proposal_layer_py
  File "/home/tp/MSDN-master/faster_rcnn/rpn_msr/proposal_layer.py", line 11, in <module>
    from ..fast_rcnn.config import cfg
ValueError: Attempted relative import beyond toplevel package






runing:./eval.sh


  [ 17  60  51]
  [  7  29  24]
  [ 51  65  61]]]
/home/tp/MSDN-master/faster_rcnn/RPN.py:140: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob = F.softmax(rpn_cls_score_reshape)
/home/tp/.local/lib/python2.7/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/tp/MSDN-master/faster_rcnn/MSDN.py:283: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob_object = F.softmax(cls_score_object)
/home/tp/MSDN-master/faster_rcnn/MSDN.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob_predicate = F.softmax(cls_score_predicate)
/home/tp/MSDN-master/faster_rcnn/MSDN.py:339: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  caption_logprobs = F.log_softmax(cls_objectiveness_region)[:, 1].squeeze().cpu().data
Traceback (most recent call last):
  File "train_hdn.py", line 394, in <module>
    main()
  File "train_hdn.py", line 191, in main
    recall = test(test_loader, net, top_Ns)
  File "train_hdn.py", line 374, in test
    top_Ns = top_Ns, nms=True)
  File "/home/tp/MSDN-master/faster_rcnn/MSDN.py", line 617, in evaluate
    nms=nms, top_N=max(top_Ns), use_gt_boxes=use_gt_boxes)
  File "/home/tp/MSDN-master/faster_rcnn/MSDN.py", line 430, in interpret_HDN
    pred_boxes = bbox_transform_inv_hdn(boxes, box_deltas)
  File "/home/tp/MSDN-master/faster_rcnn/fast_rcnn/bbox_transform.py", line 89, in bbox_transform_inv_hdn
    boxes = boxes.astype(deltas.dtype, copy=False)  #astype()对数据类型进行转换
AttributeError: 'Tensor' object has no attribute 'astype'






Do you know how to handle this three errors?　


　　　　　　　　　　　　　　　Thank you very much！　　　





在 2019-11-19 17:53:42，"LI Yikang" <notifications@github.com> 写道：


Use pytorch version 0.4.1

hello, Do you know the version of python and cuda with MSDN? thank you !

python 2.7
