### ISSUE TITLE
About Inverse Weight

### ISSUE THREAD

**Issue by LynnCtt** [yikang-li/MSDN#3]
Hello,
thank for your beautiful codes.

I want to ask you for how can I by myself transform the 'objects' and 'predicate' from unicode to float?
Is there some function that can be used to do it?

Now I'm trying to use your code with ImageNet. I can't find in the Internet how to get the inverse weight.

I'm looking forward to your answer.

Thank you.

**Comment by yikang-li** [comment]
Inverse weights are from the frequency of "predicate" and "object" categories: 1 / sqrt(freq_i). In addition, we normalize the minimum weight as 1 and scale the others accordingly.
