### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by vuongle2** [yikang-li/MSDN#8]
I am detecting some memory issue when running evaluation on Cuda 9. There is a GPU mem leaks in which the image tensor did not get release after a batch.
On cuda 8 the issue did not appear.

**Comment by vuongle2** [comment]
I found out this issue is caused by incompatibility of pytorch 0.3.1 code with 0.4 lib.

**Comment by yikang-li** [comment]
Thanks for pointing out!
