### ISSUE TITLE
Trafic limits error occurs when attempting to download full pre-trained network

### ISSUE THREAD

**Issue by chickenbestlover** [yikang-li/MSDN#9]
Hello, Thank you for your great article and source code.
When I click on the Full pre-trained network link you provided, I get the following error: What should I do?

![image](https://user-images.githubusercontent.com/10328020/41697729-1c492034-7555-11e8-801e-77d6b44f917a.png)

**Comment by tckrishna** [comment]
Hi,
I am also getting the same error. I have been checking it for the past few days and still see the same page. Is there a possible work around?

Thanks and Kudos to the great work.

**Comment by yikang-li** [comment]
Solved! Thanks for reminding!
